export type Country = {
  name: string;
  iso: string;
  dial: string;
  flag: string;
  lengths: number[];
  format: number[] | null;
};

export const Colors = {
  light: {
    text: '#11181C',
    background: '#ffffff',
    tint: '#0a7ea4',
    icon: '#687076',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: '#ffffff',
    icon: '#9BA1A6',
  },
} as const;

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", iso: "AF", dial: "+93", flag: "🇦🇫", lengths: [9], format: [3, 3, 3] },
  { name: "Albania", iso: "AL", dial: "+355", flag: "🇦🇱", lengths: [8, 9], format: null },
  { name: "Algeria", iso: "DZ", dial: "+213", flag: "🇩🇿", lengths: [8, 9], format: [3, 4, 2] },
  { name: "American Samoa", iso: "AS", dial: "+1-684", flag: "🇦🇸", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Andorra", iso: "AD", dial: "+376", flag: "🇦🇩", lengths: [6], format: [3, 3] },
  { name: "Angola", iso: "AO", dial: "+244", flag: "🇦🇴", lengths: [9], format: [3, 3, 3] },
  { name: "Anguilla", iso: "AI", dial: "+1-264", flag: "🇦🇮", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Antarctica", iso: "AQ", dial: "+672", flag: "🇦🇶", lengths: [6, 7, 8, 9, 10, 11, 12], format: null },
  { name: "Antigua and Barbuda", iso: "AG", dial: "+1-268", flag: "🇦🇬", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Argentina", iso: "AR", dial: "+54", flag: "🇦🇷", lengths: [10], format: [3, 3, 4] },
  { name: "Armenia", iso: "AM", dial: "+374", flag: "🇦🇲", lengths: [8], format: [3, 3, 2] },
  { name: "Aruba", iso: "AW", dial: "+297", flag: "🇦🇼", lengths: [7], format: [3, 4] },
  { name: "Australia", iso: "AU", dial: "+61", flag: "🇦🇺", lengths: [9, 10], format: [4, 3, 3] },
  { name: "Austria", iso: "AT", dial: "+43", flag: "🇦🇹", lengths: [7, 8, 9, 10], format: null },
  { name: "Azerbaijan", iso: "AZ", dial: "+994", flag: "🇦🇿", lengths: [9], format: [3, 3, 3] },
  { name: "Bahamas", iso: "BS", dial: "+1-242", flag: "🇧🇸", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Bahrain", iso: "BH", dial: "+973", flag: "🇧🇭", lengths: [8], format: [3, 3, 2] },
  { name: "Bangladesh", iso: "BD", dial: "+880", flag: "🇧🇩", lengths: [10], format: [4, 4, 3] },
  { name: "Barbados", iso: "BB", dial: "+1-246", flag: "🇧🇧", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Belarus", iso: "BY", dial: "+375", flag: "🇧🇾", lengths: [9], format: [3, 3, 3] },
  { name: "Belgium", iso: "BE", dial: "+32", flag: "🇧🇪", lengths: [8, 9], format: [3, 3, 3] },
  { name: "Belize", iso: "BZ", dial: "+501", flag: "🇧🇿", lengths: [7], format: [3, 4] },
  { name: "Benin", iso: "BJ", dial: "+229", flag: "🇧🇯", lengths: [8], format: [3, 3, 2] },
  { name: "Bermuda", iso: "BM", dial: "+1-441", flag: "🇧🇲", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Bhutan", iso: "BT", dial: "+975", flag: "🇧🇹", lengths: [8], format: [2, 3, 3] },
  { name: "Bolivia", iso: "BO", dial: "+591", flag: "🇧🇴", lengths: [8], format: [3, 3, 2] },
  { name: "Bosnia and Herzegovina", iso: "BA", dial: "+387", flag: "🇧🇦", lengths: [8], format: [3, 3, 2] },
  { name: "Botswana", iso: "BW", dial: "+267", flag: "🇧🇼", lengths: [7, 8], format: [3, 4] },
  { name: "Brazil", iso: "BR", dial: "+55", flag: "🇧🇷", lengths: [10, 11], format: [2, 4, 4] },
  { name: "British Indian Ocean Territory", iso: "IO", dial: "+246", flag: "🇮🇴", lengths: [7], format: [3, 4] },
  { name: "British Virgin Islands", iso: "VG", dial: "+1-284", flag: "🇻🇬", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Brunei", iso: "BN", dial: "+673", flag: "🇧🇳", lengths: [7], format: [3, 4] },
  { name: "Bulgaria", iso: "BG", dial: "+359", flag: "🇧🇬", lengths: [8, 9], format: [3, 3, 3] },
  { name: "Burkina Faso", iso: "BF", dial: "+226", flag: "🇧🇫", lengths: [8], format: [3, 3, 2] },
  { name: "Burundi", iso: "BI", dial: "+257", flag: "🇧🇮", lengths: [8], format: [3, 3, 2] },
  { name: "Cambodia", iso: "KH", dial: "+855", flag: "🇰🇭", lengths: [8, 9], format: [3, 3, 3] },
  { name: "Cameroon", iso: "CM", dial: "+237", flag: "🇨🇲", lengths: [9], format: [3, 3, 3] },
  { name: "Canada", iso: "CA", dial: "+1", flag: "🇨🇦", lengths: [10], format: [3, 3, 4] },
  { name: "Cape Verde", iso: "CV", dial: "+238", flag: "🇨🇻", lengths: [7], format: [3, 4] },
  { name: "Cayman Islands", iso: "KY", dial: "+1-345", flag: "🇰🇾", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Central African Republic", iso: "CF", dial: "+236", flag: "🇨🇫", lengths: [8], format: [3, 3, 2] },
  { name: "Chad", iso: "TD", dial: "+235", flag: "🇹🇩", lengths: [8], format: [3, 3, 2] },
  { name: "Chile", iso: "CL", dial: "+56", flag: "🇨🇱", lengths: [9], format: [1, 4, 4] },
  { name: "China", iso: "CN", dial: "+86", flag: "🇨🇳", lengths: [11], format: [3, 4, 4] },
  { name: "Christmas Island", iso: "CX", dial: "+61", flag: "🇨🇽", lengths: [7], format: [3, 4] },
  { name: "Cocos (Keeling) Islands", iso: "CC", dial: "+61", flag: "🇨🇨", lengths: [7], format: [3, 4] },
  { name: "Colombia", iso: "CO", dial: "+57", flag: "🇨🇴", lengths: [10], format: [3, 3, 4] },
  { name: "Comoros", iso: "KM", dial: "+269", flag: "🇰🇲", lengths: [7], format: [3, 4] },
  { name: "Congo (DRC)", iso: "CD", dial: "+243", flag: "🇨🇩", lengths: [9], format: [3, 3, 3] },
  { name: "Congo (Republic)", iso: "CG", dial: "+242", flag: "🇨🇬", lengths: [9], format: [3, 3, 3] },
  { name: "Cook Islands", iso: "CK", dial: "+682", flag: "🇨🇰", lengths: [5], format: [3, 2] },
  { name: "Costa Rica", iso: "CR", dial: "+506", flag: "🇨🇷", lengths: [8], format: [3, 3, 2] },
  { name: "Côte d'Ivoire", iso: "CI", dial: "+225", flag: "🇨🇮", lengths: [8, 10], format: [2, 2, 2, 2] },
  { name: "Croatia", iso: "HR", dial: "+385", flag: "🇭🇷", lengths: [8, 9], format: [3, 3, 3] },
  { name: "Cuba", iso: "CU", dial: "+53", flag: "🇨🇺", lengths: [8], format: [3, 3, 2] },
  { name: "Curaçao", iso: "CW", dial: "+599", flag: "🇨🇼", lengths: [7], format: [3, 4] },
  { name: "Cyprus", iso: "CY", dial: "+357", flag: "🇨🇾", lengths: [8], format: [3, 3, 2] },
  { name: "Czech Republic", iso: "CZ", dial: "+420", flag: "🇨🇿", lengths: [9], format: [3, 3, 3] },
  { name: "Denmark", iso: "DK", dial: "+45", flag: "🇩🇰", lengths: [8], format: [2, 2, 2, 2] },
  { name: "Djibouti", iso: "DJ", dial: "+253", flag: "🇩🇯", lengths: [8], format: [3, 3, 2] },
  { name: "Dominica", iso: "DM", dial: "+1-767", flag: "🇩🇲", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Dominican Republic", iso: "DO", dial: "+1-809", flag: "🇩🇴", lengths: [10], format: [3, 3, 4] },
  { name: "Ecuador", iso: "EC", dial: "+593", flag: "🇪🇨", lengths: [8, 9], format: null },
  { name: "Egypt", iso: "EG", dial: "+20", flag: "🇪🇬", lengths: [10], format: [3, 4, 3] },
  { name: "El Salvador", iso: "SV", dial: "+503", flag: "🇸🇻", lengths: [8], format: [3, 3, 2] },
  { name: "Equatorial Guinea", iso: "GQ", dial: "+240", flag: "🇬🇶", lengths: [9], format: [3, 3, 3] },
  { name: "Eritrea", iso: "ER", dial: "+291", flag: "🇪🇷", lengths: [7], format: [3, 4] },
  { name: "Estonia", iso: "EE", dial: "+372", flag: "🇪🇪", lengths: [7, 8], format: [3, 4] },
  { name: "Eswatini", iso: "SZ", dial: "+268", flag: "🇸🇿", lengths: [8], format: [3, 3, 2] },
  { name: "Ethiopia", iso: "ET", dial: "+251", flag: "🇪🇹", lengths: [9], format: [3, 3, 3] },
  { name: "Falkland Islands", iso: "FK", dial: "+500", flag: "🇫🇰", lengths: [5], format: [3, 2] },
  { name: "Faroe Islands", iso: "FO", dial: "+298", flag: "🇫🇴", lengths: [6], format: [3, 3] },
  { name: "Fiji", iso: "FJ", dial: "+679", flag: "🇫🇯", lengths: [7], format: [3, 4] },
  { name: "Finland", iso: "FI", dial: "+358", flag: "🇫🇮", lengths: [8, 9], format: [3, 3, 3] },
  { name: "France", iso: "FR", dial: "+33", flag: "🇫🇷", lengths: [9], format: null },
  { name: "French Guiana", iso: "GF", dial: "+594", flag: "🇬🇫", lengths: [9], format: [3, 3, 3] },
  { name: "French Polynesia", iso: "PF", dial: "+689", flag: "🇵🇫", lengths: [8], format: [3, 3, 2] },
  { name: "Gabon", iso: "GA", dial: "+241", flag: "🇬🇦", lengths: [8], format: [3, 3, 2] },
  { name: "Gambia", iso: "GM", dial: "+220", flag: "🇬🇲", lengths: [7], format: [3, 4] },
  { name: "Georgia", iso: "GE", dial: "+995", flag: "🇬🇪", lengths: [9], format: [3, 3, 3] },
  { name: "Germany", iso: "DE", dial: "+49", flag: "🇩🇪", lengths: [9, 10, 11], format: null },
  { name: "Ghana", iso: "GH", dial: "+233", flag: "🇬🇭", lengths: [9], format: [3, 3, 3] },
  { name: "Gibraltar", iso: "GI", dial: "+350", flag: "🇬🇮", lengths: [8], format: [3, 3, 2] },
  { name: "Greece", iso: "GR", dial: "+30", flag: "🇬🇷", lengths: [10], format: [3, 3, 4] },
  { name: "Greenland", iso: "GL", dial: "+299", flag: "🇬🇱", lengths: [6], format: [3, 3] },
  { name: "Grenada", iso: "GD", dial: "+1-473", flag: "🇬🇩", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Guadeloupe", iso: "GP", dial: "+590", flag: "🇬🇵", lengths: [9], format: [3, 3, 3] },
  { name: "Guam", iso: "GU", dial: "+1-671", flag: "🇬🇺", lengths: [10], format: [3, 3, 4] },
  { name: "Guatemala", iso: "GT", dial: "+502", flag: "🇬🇹", lengths: [8], format: [3, 3, 2] },
  { name: "Guernsey", iso: "GG", dial: "+44", flag: "🇬🇬", lengths: [7, 8, 10], format: null },
  { name: "Guinea", iso: "GN", dial: "+224", flag: "🇬🇳", lengths: [9], format: [3, 3, 3] },
  { name: "Guinea-Bissau", iso: "GW", dial: "+245", flag: "🇬🇼", lengths: [9], format: [3, 3, 3] },
  { name: "Guyana", iso: "GY", dial: "+592", flag: "🇬🇾", lengths: [7], format: [3, 4] },
  { name: "Haiti", iso: "HT", dial: "+509", flag: "🇭🇹", lengths: [8], format: [3, 3, 2] },
  { name: "Honduras", iso: "HN", dial: "+504", flag: "🇭🇳", lengths: [8], format: [3, 3, 2] },
  { name: "Hong Kong", iso: "HK", dial: "+852", flag: "🇭🇰", lengths: [8], format: [4, 4] },
  { name: "Hungary", iso: "HU", dial: "+36", flag: "🇭🇺", lengths: [8, 9], format: [3, 3, 3] },
  { name: "Iceland", iso: "IS", dial: "+354", flag: "🇮🇸", lengths: [7], format: [3, 4] },
  { name: "India", iso: "IN", dial: "+91", flag: "🇮🇳", lengths: [10], format: [5, 5] },
  { name: "Indonesia", iso: "ID", dial: "+62", flag: "🇮🇩", lengths: [9, 10, 11, 12, 13], format: null },
  { name: "Iran", iso: "IR", dial: "+98", flag: "🇮🇷", lengths: [10], format: [3, 3, 4] },
  { name: "Iraq", iso: "IQ", dial: "+964", flag: "🇮🇶", lengths: [10], format: [3, 3, 4] },
  { name: "Ireland", iso: "IE", dial: "+353", flag: "🇮🇪", lengths: [7, 8, 9], format: null },
  { name: "Isle of Man", iso: "IM", dial: "+44", flag: "🇮🇲", lengths: [6], format: [3, 3] },
  { name: "Israel", iso: "IL", dial: "+972", flag: "🇮🇱", lengths: [9], format: [3, 3, 3] },
  { name: "Italy", iso: "IT", dial: "+39", flag: "🇮🇹", lengths: [9, 10], format: [3, 3, 4] },
  { name: "Jamaica", iso: "JM", dial: "+1-876", flag: "🇯🇲", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Japan", iso: "JP", dial: "+81", flag: "🇯🇵", lengths: [10], format: [3, 3, 4] },
  { name: "Jersey", iso: "JE", dial: "+44", flag: "🇯🇪", lengths: [7, 8, 10], format: null },
  { name: "Jordan", iso: "JO", dial: "+962", flag: "🇯🇴", lengths: [9], format: [3, 3, 3] },
  { name: "Kazakhstan", iso: "KZ", dial: "+7", flag: "🇰🇿", lengths: [10], format: [3, 3, 4] },
  { name: "Kenya", iso: "KE", dial: "+254", flag: "🇰🇪", lengths: [9], format: [3, 3, 3] },
  { name: "Kiribati", iso: "KI", dial: "+686", flag: "🇰🇮", lengths: [5, 8], format: null },
  { name: "Kosovo", iso: "XK", dial: "+383", flag: "🇽🇰", lengths: [8, 9], format: null },
  { name: "Kuwait", iso: "KW", dial: "+965", flag: "🇰🇼", lengths: [8], format: [4, 4] },
  { name: "Kyrgyzstan", iso: "KG", dial: "+996", flag: "🇰🇬", lengths: [9], format: [3, 3, 3] },
  { name: "Laos", iso: "LA", dial: "+856", flag: "🇱🇦", lengths: [8, 10], format: null },
  { name: "Latvia", iso: "LV", dial: "+371", flag: "🇱🇻", lengths: [8], format: [3, 3, 2] },
  { name: "Lebanon", iso: "LB", dial: "+961", flag: "🇱🇧", lengths: [7, 8], format: null },
  { name: "Lesotho", iso: "LS", dial: "+266", flag: "🇱🇸", lengths: [8], format: [3, 3, 2] },
  { name: "Liberia", iso: "LR", dial: "+231", flag: "🇱🇷", lengths: [7, 8], format: null },
  { name: "Libya", iso: "LY", dial: "+218", flag: "🇱🇾", lengths: [9], format: [3, 3, 3] },
  { name: "Liechtenstein", iso: "LI", dial: "+423", flag: "🇱🇮", lengths: [7], format: [3, 4] },
  { name: "Lithuania", iso: "LT", dial: "+370", flag: "🇱🇹", lengths: [8], format: [3, 3, 2] },
  { name: "Luxembourg", iso: "LU", dial: "+352", flag: "🇱🇺", lengths: [9], format: [3, 3, 3] },
  { name: "Macau", iso: "MO", dial: "+853", flag: "🇲🇴", lengths: [8], format: [4, 4] },
  { name: "Madagascar", iso: "MG", dial: "+261", flag: "🇲🇬", lengths: [9], format: [3, 3, 3] },
  { name: "Malawi", iso: "MW", dial: "+265", flag: "🇲🇼", lengths: [9], format: [3, 3, 3] },
  { name: "Malaysia", iso: "MY", dial: "+60", flag: "🇲🇾", lengths: [9, 10], format: [3, 3, 4] },
  { name: "Maldives", iso: "MV", dial: "+960", flag: "🇲🇻", lengths: [7], format: [3, 4] },
  { name: "Mali", iso: "ML", dial: "+223", flag: "🇲🇱", lengths: [8], format: [3, 3, 2] },
  { name: "Malta", iso: "MT", dial: "+356", flag: "🇲🇹", lengths: [8], format: [3, 3, 2] },
  { name: "Marshall Islands", iso: "MH", dial: "+692", flag: "🇲🇭", lengths: [7], format: [3, 4] },
  { name: "Martinique", iso: "MQ", dial: "+596", flag: "🇲🇶", lengths: [9], format: [3, 3, 3] },
  { name: "Mauritania", iso: "MR", dial: "+222", flag: "🇲🇷", lengths: [8], format: [3, 3, 2] },
  { name: "Mauritius", iso: "MU", dial: "+230", flag: "🇲🇺", lengths: [7, 8], format: null },
  { name: "Mayotte", iso: "YT", dial: "+262", flag: "🇾🇹", lengths: [9], format: [3, 3, 3] },
  { name: "Mexico", iso: "MX", dial: "+52", flag: "🇲🇽", lengths: [10], format: [2, 4, 4] },
  { name: "Micronesia", iso: "FM", dial: "+691", flag: "🇫🇲", lengths: [7], format: [3, 4] },
  { name: "Moldova", iso: "MD", dial: "+373", flag: "🇲🇩", lengths: [8], format: [3, 3, 2] },
  { name: "Monaco", iso: "MC", dial: "+377", flag: "🇲🇨", lengths: [8, 9], format: null },
  { name: "Mongolia", iso: "MN", dial: "+976", flag: "🇲🇳", lengths: [8], format: [3, 3, 2] },
  { name: "Montenegro", iso: "ME", dial: "+382", flag: "🇲🇪", lengths: [8], format: [3, 3, 2] },
  { name: "Montserrat", iso: "MS", dial: "+1-664", flag: "🇲🇸", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Morocco", iso: "MA", dial: "+212", flag: "🇲🇦", lengths: [9], format: [3, 3, 3] },
  { name: "Mozambique", iso: "MZ", dial: "+258", flag: "🇲🇿", lengths: [8, 9], format: null },
  { name: "Myanmar", iso: "MM", dial: "+95", flag: "🇲🇲", lengths: [8, 9, 10], format: null },
  { name: "Namibia", iso: "NA", dial: "+264", flag: "🇳🇦", lengths: [9], format: [3, 3, 3] },
  { name: "Nauru", iso: "NR", dial: "+674", flag: "🇳🇷", lengths: [7], format: [3, 4] },
  { name: "Nepal", iso: "NP", dial: "+977", flag: "🇳🇵", lengths: [10], format: [3, 4, 3] },
  { name: "Netherlands", iso: "NL", dial: "+31", flag: "🇳🇱", lengths: [9], format: [2, 3, 4] },
  { name: "New Caledonia", iso: "NC", dial: "+687", flag: "🇳🇨", lengths: [6], format: [3, 3] },
  { name: "New Zealand", iso: "NZ", dial: "+64", flag: "🇳🇿", lengths: [8, 9, 10], format: null },
  { name: "Nicaragua", iso: "NI", dial: "+505", flag: "🇳🇮", lengths: [8], format: [3, 3, 2] },
  { name: "Niger", iso: "NE", dial: "+227", flag: "🇳🇪", lengths: [8], format: [3, 3, 2] },
  { name: "Nigeria", iso: "NG", dial: "+234", flag: "🇳🇬", lengths: [10], format: [4, 3, 3] },
  { name: "Niue", iso: "NU", dial: "+683", flag: "🇳🇺", lengths: [4], format: [2, 2] },
  { name: "North Korea", iso: "KP", dial: "+850", flag: "🇰🇵", lengths: [8, 10, 11], format: null },
  { name: "North Macedonia", iso: "MK", dial: "+389", flag: "🇲🇰", lengths: [8], format: [3, 3, 2] },
  { name: "Northern Mariana Islands", iso: "MP", dial: "+1-670", flag: "🇲🇵", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Norway", iso: "NO", dial: "+47", flag: "🇳🇴", lengths: [8], format: [3, 2, 3] },
  { name: "Oman", iso: "OM", dial: "+968", flag: "🇴🇲", lengths: [8], format: [3, 3, 2] },
  { name: "Pakistan", iso: "PK", dial: "+92", flag: "🇵🇰", lengths: [10], format: [4, 3, 3] },
  { name: "Palau", iso: "PW", dial: "+680", flag: "🇵🇼", lengths: [7], format: [3, 4] },
  { name: "Palestine", iso: "PS", dial: "+970", flag: "🇵🇸", lengths: [9], format: [3, 3, 3] },
  { name: "Panama", iso: "PA", dial: "+507", flag: "🇵🇦", lengths: [8], format: [3, 3, 2] },
  { name: "Papua New Guinea", iso: "PG", dial: "+675", flag: "🇵🇬", lengths: [7, 8], format: null },
  { name: "Paraguay", iso: "PY", dial: "+595", flag: "🇵🇾", lengths: [9], format: [3, 3, 3] },
  { name: "Peru", iso: "PE", dial: "+51", flag: "🇵🇪", lengths: [9], format: [3, 3, 3] },
  { name: "Philippines", iso: "PH", dial: "+63", flag: "🇵🇭", lengths: [10], format: [4, 3, 3] },
  { name: "Poland", iso: "PL", dial: "+48", flag: "🇵🇱", lengths: [9], format: [3, 3, 3] },
  { name: "Portugal", iso: "PT", dial: "+351", flag: "🇵🇹", lengths: [9], format: [3, 3, 3] },
  { name: "Puerto Rico", iso: "PR", dial: "+1-787", flag: "🇵🇷", lengths: [10], format: [3, 3, 4] },
  { name: "Qatar", iso: "QA", dial: "+974", flag: "🇶🇦", lengths: [8], format: [2, 2, 2, 2] },
  { name: "Réunion", iso: "RE", dial: "+262", flag: "🇷🇪", lengths: [9], format: [3, 3, 3] },
  { name: "Romania", iso: "RO", dial: "+40", flag: "🇷🇴", lengths: [9], format: [3, 3, 3] },
  { name: "Russia", iso: "RU", dial: "+7", flag: "🇷🇺", lengths: [10], format: [3, 3, 2, 2] },
  { name: "Rwanda", iso: "RW", dial: "+250", flag: "🇷🇼", lengths: [9], format: [3, 3, 3] },
  { name: "Saint Barthélemy", iso: "BL", dial: "+590", flag: "🇧🇱", lengths: [9], format: [3, 3, 3] },
  { name: "Saint Helena", iso: "SH", dial: "+290", flag: "🇸🇭", lengths: [4, 5], format: null },
  { name: "Saint Kitts and Nevis", iso: "KN", dial: "+1-869", flag: "🇰🇳", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Saint Lucia", iso: "LC", dial: "+1-758", flag: "🇱🇨", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Saint Martin", iso: "MF", dial: "+590", flag: "🇲🇫", lengths: [9], format: [3, 3, 3] },
  { name: "Saint Pierre and Miquelon", iso: "PM", dial: "+508", flag: "🇵🇲", lengths: [6], format: [3, 3] },
  { name: "Saint Vincent and the Grenadines", iso: "VC", dial: "+1-784", flag: "🇻🇨", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Samoa", iso: "WS", dial: "+685", flag: "🇼🇸", lengths: [7], format: [3, 4] },
  { name: "San Marino", iso: "SM", dial: "+378", flag: "🇸🇲", lengths: [9, 10], format: null },
  { name: "São Tomé and Príncipe", iso: "ST", dial: "+239", flag: "🇸🇹", lengths: [7], format: [3, 4] },
  { name: "Saudi Arabia", iso: "SA", dial: "+966", flag: "🇸🇦", lengths: [9], format: [3, 3, 3] },
  { name: "Senegal", iso: "SN", dial: "+221", flag: "🇸🇳", lengths: [9], format: [3, 3, 3] },
  { name: "Serbia", iso: "RS", dial: "+381", flag: "🇷🇸", lengths: [9, 10], format: null },
  { name: "Seychelles", iso: "SC", dial: "+248", flag: "🇸🇨", lengths: [7], format: [3, 4] },
  { name: "Sierra Leone", iso: "SL", dial: "+232", flag: "🇸🇱", lengths: [8], format: [3, 3, 2] },
  { name: "Singapore", iso: "SG", dial: "+65", flag: "🇸🇬", lengths: [8], format: [4, 4] },
  { name: "Sint Maarten", iso: "SX", dial: "+1-721", flag: "🇸🇽", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Slovakia", iso: "SK", dial: "+421", flag: "🇸🇰", lengths: [9], format: [3, 3, 3] },
  { name: "Slovenia", iso: "SI", dial: "+386", flag: "🇸🇮", lengths: [8], format: [3, 3, 2] },
  { name: "Solomon Islands", iso: "SB", dial: "+677", flag: "🇸🇧", lengths: [7], format: [3, 4] },
  { name: "Somalia", iso: "SO", dial: "+252", flag: "🇸🇴", lengths: [8, 9], format: null },
  { name: "South Africa", iso: "ZA", dial: "+27", flag: "🇿🇦", lengths: [9], format: [3, 3, 3] },
  { name: "South Korea", iso: "KR", dial: "+82", flag: "🇰🇷", lengths: [10, 11], format: [3, 4, 4] },
  { name: "South Sudan", iso: "SS", dial: "+211", flag: "🇸🇸", lengths: [9], format: [3, 3, 3] },
  { name: "Spain", iso: "ES", dial: "+34", flag: "🇪🇸", lengths: [9], format: [3, 2, 2, 2] },
  { name: "Sri Lanka", iso: "LK", dial: "+94", flag: "🇱🇰", lengths: [9], format: [3, 3, 3] },
  { name: "Sudan", iso: "SD", dial: "+249", flag: "🇸🇩", lengths: [9], format: [3, 3, 3] },
  { name: "Suriname", iso: "SR", dial: "+597", flag: "🇸🇷", lengths: [7], format: [3, 4] },
  { name: "Svalbard and Jan Mayen", iso: "SJ", dial: "+47", flag: "🇸🇯", lengths: [8], format: [3, 3, 2] },
  { name: "Sweden", iso: "SE", dial: "+46", flag: "🇸🇪", lengths: [8, 9, 10], format: null },
  { name: "Switzerland", iso: "CH", dial: "+41", flag: "🇨🇭", lengths: [9], format: [3, 2, 2, 2] },
  { name: "Syria", iso: "SY", dial: "+963", flag: "🇸🇾", lengths: [9], format: [3, 3, 3] },
  { name: "Taiwan", iso: "TW", dial: "+886", flag: "🇹🇼", lengths: [9], format: [4, 3, 3] },
  { name: "Tajikistan", iso: "TJ", dial: "+992", flag: "🇹🇯", lengths: [9], format: [3, 3, 3] },
  { name: "Tanzania", iso: "TZ", dial: "+255", flag: "🇹🇿", lengths: [9], format: [3, 3, 3] },
  { name: "Thailand", iso: "TH", dial: "+66", flag: "🇹🇭", lengths: [9], format: [3, 3, 3] },
  { name: "Timor-Leste", iso: "TL", dial: "+670", flag: "🇹🇱", lengths: [7, 8], format: null },
  { name: "Togo", iso: "TG", dial: "+228", flag: "🇹🇬", lengths: [8], format: [3, 3, 2] },
  { name: "Tokelau", iso: "TK", dial: "+690", flag: "🇹🇰", lengths: [4], format: [2, 2] },
  { name: "Tonga", iso: "TO", dial: "+676", flag: "🇹🇴", lengths: [7], format: [3, 4] },
  { name: "Trinidad and Tobago", iso: "TT", dial: "+1-868", flag: "🇹🇹", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Tunisia", iso: "TN", dial: "+216", flag: "🇹🇳", lengths: [8], format: [3, 3, 2] },
  { name: "Turkey", iso: "TR", dial: "+90", flag: "🇹🇷", lengths: [10], format: [3, 3, 4] },
  { name: "Turkmenistan", iso: "TM", dial: "+993", flag: "🇹🇲", lengths: [8], format: [3, 3, 2] },
  { name: "Turks and Caicos Islands", iso: "TC", dial: "+1-649", flag: "🇹🇨", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Tuvalu", iso: "TV", dial: "+688", flag: "🇹🇻", lengths: [7], format: [3, 4] },
  { name: "Uganda", iso: "UG", dial: "+256", flag: "🇺🇬", lengths: [9], format: [3, 3, 3] },
  { name: "Ukraine", iso: "UA", dial: "+380", flag: "🇺🇦", lengths: [9], format: [3, 2, 2, 2] },
  { name: "United Arab Emirates", iso: "AE", dial: "+971", flag: "🇦🇪", lengths: [9], format: [3, 3, 3] },
  { name: "United Kingdom", iso: "GB", dial: "+44", flag: "🇬🇧", lengths: [10], format: [5, 5] },
  { name: "United States", iso: "US", dial: "+1", flag: "🇺🇸", lengths: [10], format: [3, 3, 4] },
  { name: "Uruguay", iso: "UY", dial: "+598", flag: "🇺🇾", lengths: [8], format: [2, 3, 3] },
  { name: "U.S. Virgin Islands", iso: "VI", dial: "+1-340", flag: "🇻🇮", lengths: [7, 10], format: [3, 3, 4] },
  { name: "Uzbekistan", iso: "UZ", dial: "+998", flag: "🇺🇿", lengths: [9], format: [3, 3, 3] },
  { name: "Vanuatu", iso: "VU", dial: "+678", flag: "🇻🇺", lengths: [7], format: [3, 4] },
  { name: "Vatican City", iso: "VA", dial: "+39", flag: "🇻🇦", lengths: [10], format: [3, 3, 4] },
  { name: "Venezuela", iso: "VE", dial: "+58", flag: "🇻🇪", lengths: [10], format: [4, 3, 2, 2] },
  { name: "Vietnam", iso: "VN", dial: "+84", flag: "🇻🇳", lengths: [9, 10], format: [3, 4, 3] },
  { name: "Wallis and Futuna", iso: "WF", dial: "+681", flag: "🇼🇫", lengths: [6], format: [3, 3] },
  { name: "Western Sahara", iso: "EH", dial: "+212", flag: "🇪🇭", lengths: [9], format: [3, 3, 3] },
  { name: "Yemen", iso: "YE", dial: "+967", flag: "🇾🇪", lengths: [9], format: [3, 3, 3] },
  { name: "Zambia", iso: "ZM", dial: "+260", flag: "🇿🇲", lengths: [9], format: [3, 3, 3] },
  { name: "Zimbabwe", iso: "ZW", dial: "+263", flag: "🇿🇼", lengths: [9], format: [3, 3, 3] },
];